# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44e3074865e65c4afa11888fb7736bcf495ba8a8ec63434c8a3df2e55e18ec2b04eb7649f1bc648fc6faae14a50e2f70dee5cba92742629a17135f0114acd0f6

test:
  secret_key_base: 0e044c275823b6485ee58809d9e4a8063f78911187da63ecc299b5d6d6136bd623f64d74deaeeeced888ac86d577848a4a953bfdeaf4a2faebf8f993b725ae34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
